language: go

go:
  - 1.9.x
  - master

before_install:
  - git submodule update --init --remote --recursive

install:
  - go get github.com/kardianos/govendor
  - govendor get github.com/gohugoio/hugo

script:
  - hugo
  - echo "blog.ageekymonk.com" > public/CNAME

branches:
  only:
  - source

default_branch: source

deploy:
  skip_cleanup: true
  name: travis
  email: deploy@travis-ci.org
  provider: pages
  github_token: $GITHUB_TOKEN
  target_branch: master
  local_dir: public
  on:
    branch: source
